### ISSUE TITLE
과일이 뱀의 몸통 부분에 생성되는 문제

### ISSUE THREAD

**Issue by SonHyeWon** [SonHyeWon/SnakeGame#36]
##문제 파트 및 상황 서술##
게임에서 과일이 생성은 createFruit 함수에서 수행됩니다.
이때, createFruit 함수에서 과일의 좌표 할당 조건은 '맵 내부에 위치할 것' 뿐입니다.
때문에 뱀의 몸통 부분에 과일이 생성되기도 하고, 그럴 경우 사용자는 아무 방향으로 뱀을 이동시켜 과일의 위치를 확인한 후 다시 이동해야 하는 문제가 발생합니다.

##원하는 작동 방식##
createFruit 함수 내부, 혹은 새로운 함수를 작성하여 과일에 뱀의 기존 몸통 위치와 겹치지 않는 좌표를 할당하는 것이 필요합니다.

##추가로 서술을 원하는 내용(없을 시 생략)##
이는 추가 기능으로, 구현에 대한 아이디어는 자유롭게 토론해주시면 됩니다.

**Comment by MtNight** [comment]
만약 제대로 구현한다면, 게임 공간의 모든 CELL에 순서대로 숫자를 붙인 다음, 뱀에 해당하는 숫자들을 제외하고 나머지 중에 랜덤으로 하나를 골라 생성하면 됩니다. '게임'으로 볼 때 굉장히 큰 문제라서 수정이 필요합니다만, 성능 저하를 최소화하여 만드려면 screenInfo을 건드리는 등 해야할 것들이 많아서 시간 상 구현을 하기 애매합니다.
저희 프로젝트의 핵심 목표는 클린 코드이기 때문에, 불필요하다고 생각하신다면 고치지 않아도 무방할 것 같습니다. 처음 문제를 제기한 사람으로써 여러분들의 의견을 알고 싶습니다.

**Comment by mellime** [comment]
추가하면 좋은 기능이라고 생각하지만, 시간이 촉박하다는 것이 걸리네요.
후에 시간적 여유가 있다면 추가하는 것이 어떨까요?
