### ISSUE TITLE
게임 오버 시 오브젝트 겹침 현상

### ISSUE THREAD

**Issue by MtNight** [SonHyeWon/SnakeGame#39]
##문제 파트 및 상황 서술##
현재 벽이 부딪히거나 뱀의 몸통에 닿으면 게임 오버가 되는데, 이 때 부딪힌 벽이나 몸통과 뱀 머리가 위치가 겹치게 됩니다. 보통은 겹치기 직전까지 화면이 그려지고, 겹치는 순간 사망 처리가 되어 겹친 상태까지는 그려지지 않긴 하지만... 이는 약간 주관적인 견해가 많이 포함될 여지가 있는 부분이라 팀원 분들의 의견을 듣고 싶습니다.
1. 현재 상태 유지 (사망 원인과 뱀 머리 겹침)
2. 변경 (사망 직전 상태 표시)

##원하는 작동 방식##
main.c 의 drawObject함수 호출 직전에 quit 변수를 확인해서 drawObject함수를 실행하지 않으면 상술한 상태를 그릴 수 있습니다.

##추가로 서술을 원하는 내용##
이것만 해서 사망 확인이 잘 안될 것 같다고 생각하시면, drawObject 함수에 quit을 인자로 준 다음 사망 시 뱀 색깔을 빨갛게 칠한다던가...? 와 같은 여러 방법이 있을 것 같습니다.

**Comment by hongyj9823** [comment]
저는 1번에 한 표 두겠습니다. 겹쳐서 머리만 빨갛게 표현되는 건 어떨까 싶습니다. 게임이 종료되었다는 것을 조금 눈에 띄게 표현하는 식으로 색에 변화를 주는 것은 매우 좋다고 생각합니다. 다른 분들 의견도 존중하겠습니다. 감사합니다.

**Comment by mellime** [comment]
저는 2번에 찬성하되, @hongyj9823 씨의 의견도 부분적으로 수렴하고 싶습니다. 사망 직전 상태를 표시하되, 게임 오버 시 머리 색에 변경을 주는 것은 어떨까요?

**Comment by SonHyeWon** [comment]
늦은 확인 죄송합니다. 저도 @mellime 씨 의견에 동의합니다.

**Comment by MtNight** [comment]
그럼 의견을 취합해서, 사망 직전 화면을 표시하고 머리 색만 빨갛게 표시하겠습니다! 다들 감사합니다!
